import { get } from "http";

const CommunicationEvents = Object.freeze({
    getTodoKanbanCards: "todo-cards",
    saveTodoKanbanCard: "save-todo-card",
    deleteTodoKanbanCard: "delete-todo-card",
    modifyTodoKanbanCard: "modify-todo-card",
    generateFeature: "generate-feature",
    refineFeature: "refine-feature",
    summaryFeature: "summary-feature",
    exportFeature: "export-feature",
    translateEmail: "translate-email",
    generateJira: "generate-jira",
    improveEnglish: "improve-english",
    getProductivity: "getProductivity",
    copy: "copy",
    generateToken: "generateToken",
    getVaultItems: "getVaultItems",
    saveVaultItem: "saveVaultItem",
    deleteVaultItem: "deleteVaultItem",
    modifyVaultItem: "modifyVaultItem",
    createPi: "createPi",
    deletePi: "deletePi",
    getPi: "getPi",
    createJira: "createJira",
    modifyJira: "modifyJira",
    deleteJira: "deleteJira",
    getJiraByPi: "getJiraByPi",
    getJiraByFeature: "getJiraByFeature",
    completeJira: "completeJira",
    createPlannedPi: "createPlannedPi",
    deletePlannedPi: "deletePlannedPi",
    getPlannedPi: "getPlannedPi",
    createPlannedFeature: "createPlannedFeature",
    deletePlannedFeature: "deletePlannedFeature",
    modifyPlannedFeature: "modifyPlannedFeature",
    getAllPlannedFeature: "getAllPlannedFeature"
});

export default CommunicationEvents;